title: Hello, world! I'm Mister Juan
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: im.mister.juan
author-img: logo.jpg
about-author: I am a web developer from a small island in the Philippines. Im also a licensed amateur Radio Operator with a callsign of DW7LFU
social-twitter: immisterjuan
social-facebook: nopoweb 
social-github: juancaser
social-linkedin: juancaser
social-email: hello@nopoweb.com


# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

paginate: 3
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock","Gemfile","Gemfile.local","LICENSE","README.md"]